### ISSUE TITLE
When I upgraded from 1.7.12 to 1.7.14, the client connection times was wrong.

### ISSUE THREAD

**Issue by Hholz** [mrniko/netty-socketio#551]
2018-05-05 17:13:59,361 [nioEventLoopGroup-3-48] WARN i.n.c.ChannelInitializer[151] Failed to initialize a channel. Closing: [id: 0x3471cd2e, L:/172.18.24.122:4869 - R:/14.20.91.253:12914]
java.lang.NoClassDefFoundError: Could not initialize class com.corundumstudio.socketio.SocketIOChannelInitializer$1
        at com.corundumstudio.socketio.SocketIOChannelInitializer.addSocketioHandlers(SocketIOChannelInitializer.java:169)
        at com.corundumstudio.socketio.SocketIOChannelInitializer.initChannel(SocketIOChannelInitializer.java:146)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:76)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:128)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1307)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:820)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:509)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Hholz** [comment]
The redission dependent version of netty is 4.1.13, but the netty version of netty used by netty-socketio is 4.1.25. Jar clashing occurs.Just update the redission version to the same version used by netty-socketio, or use the latest redisson version
