### ISSUE TITLE
start server exception after upgrading to 1.7.11, works fine at 1.7.10

### ISSUE THREAD

**Issue by gckjdev** [mrniko/netty-socketio#383]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.corundumstudio.socketio.Configuration.<init>(Configuration.java:109)
	... 9 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:50)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:543)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:460)
	at com.corundumstudio.socketio.protocol.JacksonJsonSupport.<init>(JacksonJsonSupport.java:297)
	at com.corundumstudio.socketio.protocol.JacksonJsonSupport.<init>(JacksonJsonSupport.java:304)
	... 14 more

**Comment by JavaMachine** [comment]
Hi, did you updated dependencies?
[v1.7.11](http://mvnrepository.com/artifact/com.corundumstudio.socketio/netty-socketio/1.7.11)
(and old [v1.7.10](http://mvnrepository.com/artifact/com.corundumstudio.socketio/netty-socketio/1.7.10) )
As you can notice 'com.fasterxml.jackson' libraries updated from 2.6.3 to 2.7.4

**Comment by mrniko** [comment]
please update jackson lib
